### ISSUE TITLE
ldc / D language port

### ISSUE THREAD

**Issue by Ace17** [emscripten-core/emscripten-fastcomp#114]
Trying to build the ldc compiler for the D language against llvm-emscripten (as a first step to D->asmjs compilation).
ldc builds fine against vanilla llvm 3.5.0, 3.6.0, 3.7.0.
However, when building ldc against master branch of emscripten-fastcomp, I get errors:

$ make
[  0%] Built target impcnvgen
[  0%] Built target idgen
[  0%] Building CXX object CMakeFiles/LDCShared.dir/gen/arrays.cpp.o
In file included from /home/ace/source/ldc/./gen/irstate.h:20:0,
                 from /home/ace/source/ldc/gen/arrays.cpp:19:
/home/ace/source/ldc/./ir/irfunction.h:130:45: error: ‘DILocalVariable’ is not a member of ‘llvm’
     typedef llvm::DenseMap<VarDeclaration*, llvm::DILocalVariable*> VariableMap;
                                             ^
/home/ace/source/ldc/./ir/irfunction.h:130:45: error: ‘DILocalVariable’ is not a member of ‘llvm’
/home/ace/source/ldc/./ir/irfunction.h:130:67: error: template argument 2 is invalid
     typedef llvm::DenseMap<VarDeclaration*, llvm::DILocalVariable*> VariableMap;
                                                                   ^
/home/ace/source/ldc/./ir/irfunction.h:130:67: error: template argument 4 is invalid
In file included from /home/ace/source/ldc/./gen/irstate.h:23:0,
                 from /home/ace/source/ldc/gen/arrays.cpp:19:
/home/ace/source/ldc/./gen/dibuilder.h:77:15: error: ‘DILocalVariable’ in namespace ‘llvm’ does not name a type
 typedef llvm::DILocalVariable\* DILocalVariable;
               ^
In file included from /home/ace/source/ldc/./gen/irstate.h:23:0,
                 from /home/ace/source/ldc/gen/arrays.cpp:19:
/home/ace/source/ldc/./gen/dibuilder.h:192:57: error: ‘ldc::DILocalVariable’ has not been declared
     void Declare(const Loc &loc, llvm::Value _var, ldc::DILocalVariable divar
                                                         ^
CMakeFiles/LDCShared.dir/build.make:1631: recipe for target 'CMakeFiles/LDCShared.dir/gen/arrays.cpp.o' failed
make[2]: *_\* [CMakeFiles/LDCShared.dir/gen/arrays.cpp.o] Error 1
CMakeFiles/Makefile2:61: recipe for target 'CMakeFiles/LDCShared.dir/all' failed
make[1]: **\* [CMakeFiles/LDCShared.dir/all] Error 2
Makefile:146: recipe for target 'all' failed
make: **\* [all] Error 2

It seems like emscripten-fastcomp reports an llvm version of 3.7.0svn but doesn't declare some symbols which were introduced in llvm version 3.7.0, like DILocalVariable.
The ldc source code relies on version numbers to enable, using #if/#else, some parts of the code. 
How can I re-align emscripten declarations to the official llvm branch?
Would it be a good idea?

**Comment by kripken** [comment]
Emscripten fastcomp is somewhere in between 3.6 and 3.7 - wherever we last took a snapshot of svn, basically. If you tell it 3.6, does it work? If not, might need to wait until we update to 3.7 (for which we are waiting on pnacl I think).

**Comment by Ace17** [comment]
I tried overriding the version number, in order for ldc to see "3.6" instead of "3.7".
However, I get other compile errors (mostly related to the debug info builder - maybe this can be disabled?), as you said, fastcomp is somewhere in between both versions.

Is there an older version of emscripten which would really be 3.6 based?

**Comment by kripken** [comment]
I would read the changelog to see where we merged LLVM versions, and try those.

A complexity here is that we merge from PNaCl, not LLVM directly. And they tend to be somewhere on trunk, not a precise LLVM release date. As a new LLVM release is almost here, we could see if PNaCl is updating, and it might be a good time to be very close to a precise LLVM release.

Or maybe ldc has versions for different points on LLVM trunk?

**Comment by Ace17** [comment]
The ldc master branch supports, through heavy preprocessor use, each official release of LLVM (3.5, 3.6, 3.7 as far as I tried).

**Comment by kripken** [comment]
I see, ok. Meanwhile I checked and it doens't look like pnacl has a recent merge from upstream. I do have a merge from pnacl in the merge_37 branches, but I'm not sure it'll help - might be worth trying though.

**Comment by kripken** [comment]
I merged those into incoming. But they don't move us much closer to llvm 3.7, yet.

The good news is that @jfbastien says PNaCl will merge 3.7 stable next, so once we merge that, you should be able to run ldc on 3.7.

**Comment by kripken** [comment]
You might want to look at the `back-to-llvm` branches in the 3 repos. Those are a wip merge of the upstream `google/stable` branches of LLVM. That's LLVM trunk from around 2 months ago, and no longer dependent on PNaCl in the middle (as PNaCl no longer has concrete update plans, so we need to move ourselves to rebase off of upstream).

Still running tests, but a big chunk of the test suite passes, so it might be worth trying if you're still blocked on this. I believe this is labeled 3.8 as it is right after the branch for 3.8, but should be very close to the official 3.7 release.

**Comment by Ace17** [comment]
Thank you! I'm trying this and I keep you informed.

**Comment by kripken** [comment]
That merge is now on incoming, after passing my tests.

**Comment by Ace17** [comment]
Still no luck:
/home/ace/source/ldc/gen/dibuilder.cpp:928:34: error: ‘class llvm::DIBuilder’ has no member named ‘createLocalVariable’

**Comment by kripken** [comment]
git history says that method was removed on

````
commit aa50fa7c2f6a22d97a11336d7281377dcfcafc9d
Author: Duncan P. N. Exon Smith <dexonsmith@apple.com>
Date:   Fri Jul 31 17:55:53 2015 +0000

    DI: Rewrite the DIBuilder local variable API
    
    Replace the general `createLocalVariable()` with two more specific
    functions: `createParameterVariable()` and `createAutoVariable()`, and
    rewrite the documentation.
    
    Besides cleaning up the API, this avoids exposing the fake DWARF tags
    `DW_TAG_arg_variable` and `DW_TAG_auto_variable` to frontends, and is
    preparation for removing them completely.
    
    git-svn-id: https://llvm.org/svn/llvm-project/llvm/trunk@243764 91177308-0d34-0410-b5e6-96231b3b80d8
````

which I think is a little after 3.8 branched. So I guess now we are too far ahead of D? Does D have a version tracking trunk?

**Comment by Ace17** [comment]
Thanks for looking it up in the history.
So now I guess the ticket title becomes "llvm-config reports version number 3.8.0svn but doesn't declare createLocalVariable" :-)

FYI, the "ldc" compiler is available on github ( https://github.com/ldc-developers/ldc ). It's compatible with all official LLVM releases (3.5, 3.6, 3.7, haven't tried 3.8 yet).

At this point, there are only two compilation errors left when compiling ldc versus emscripten. I'm going to workaround them manually. Thanks again!

**Comment by kripken** [comment]
Note that there isn't a 3.8 release yet - it's the version being developed on trunk. So I think that technically we are ok to report 3.8.0svn so long as we are anywhere along the 3.8 dev cycle ;)

But yeah, hopefully the diff should be small at this point, glad to hear there are just 2 errors left. Would be great to see this working!

Btw, we "skipped" 3.7 final because we moved from one google/stable tag to the latest, which was easiest given the large delay we had. But going forward, we should try to stay close to trunk, and so we should be able to have a tag for 3.8 final.

**Comment by Ace17** [comment]
FYI it used to work with ldc: https://gist.github.com/pszturmaj/6244260
That was two years ago ; however, the switching to fastcomp (i.e, making emscripten a LLVM backend) combined with the release version discrepancies (between LLVM and emscriten) made it a lot harder.
By the way, I see there are assertions related to PNaCl in JSBackend.cpp ; especially one ensuring constant structs are packed. Are they still relevant? Is PNaCl still a valid target?

**Comment by kripken** [comment]
Yes, once we moved to an LLVM backend it gets trickier to synchronize with other projects using their own version of LLVM. Hopefully we'll be very close to trunk from now on, which should allow projects similarly close to trunk to use emscripten. In the longer term, we hope to use the new wasm backend which is entirely upstream.

Which assertions do you mean? We use the PNaCl legalization passes, but have our own target machine etc.

**Comment by Ace17** [comment]
I'm talking about these: 
https://github.com/kripken/emscripten-fastcomp/blob/master/lib/Target/JSBackend/JSBackend.cpp#L3397

**Comment by kripken** [comment]
Ok, yes, that is code that reads the output of the PNaCl legalization passes, which is the part of PNaCl that we use.

**Comment by Ace17** [comment]
Hi there, I finally managed to compile some D code to asmjs using Emscripten:
https://github.com/Ace17/dscripten
(There's no support for the D runtime at the moment, it's only a demo SDL program)
I had to use llvm-cbe (the C backend) to convert D code back to C so it generates llvm bitcode in the subset emscripten can handle.
I also had to compile two versions of LLVM: one for emscripten/fastcomp, one for llvm-cbe and ldc.

I'd be very happy to ditch one of the two LLVM versions, as I would also be very happy to ditch the LLVM resurrected C backend. Do you have an idea of how to proceed?

**Comment by kripken** [comment]
If we can't get D code to legalize using the pnacl passes, then the other option is to try the wasm backend in upstream LLVM. See the [docs](https://github.com/kripken/emscripten/wiki/New-WebAssembly-Backend) for how to run it. For D, you'd run those commands on the bitcode file.

**Comment by Ace17** [comment]
Thanks for the idea.
I'm gonna go for the wasm backend, which seems like the long-term solution.

The docs says I don't need fastcomp, however, do I need any clang? (I would have expected not to need any version of clang, am I missing something?)
Here's what I get:

ace@ANTEC:~/projects/dscripten$ llvm-config --version
3.8.0
ace@ANTEC:~/projects/dscripten$ llvm-config --prefix
/tmp/toolchains/emsd
ace@ANTEC:~/projects/dscripten$ rm ~/.emscripten
ace@ANTEC:~/projects/dscripten$ ldc2 test.d -output-bc
ace@ANTEC:~/projects/dscripten$ llc test.bc -mtriple=wasm32
ace@ANTEC:~/projects/dscripten$ EMCC_WASM_BACKEND=1 emcc test.bc -o file.js -s BINARYEN=1 -s ONLY_MY_CODE=1

==============================================================================
Welcome to Emscripten!

This is the first time any of the Emscripten tools has been run.

A settings file has been copied to ~/.emscripten, at absolute path: /home/ace/.emscripten

It contains our best guesses for the important paths, which are:

  LLVM_ROOT       = /tmp/toolchains/emsd/bin
  NODE_JS         = /usr/bin/nodejs
  EMSCRIPTEN_ROOT = /tmp/emsd-source/emscripten

Please edit the file if any of those are incorrect.

This command will now exit. When you are done editing those paths, re-run it.
==============================================================================

ace@ANTEC:~/projects/dscripten$ EMCC_WASM_BACKEND=1 emcc test.bc -o file.js -s BINARYEN=1 -s ONLY_MY_CODE=1
WARNING:root:(Emscripten: settings file has changed, clearing cache)
WARNING:root:Could not verify LLVM version: [Errno 2] No such file or directory
CRITICAL:root:fastcomp in use, but LLVM has not been built with the JavaScript backend as a target, llc reports:
===========================================================================
LLVM (http://llvm.org/):
  LLVM version 3.8.0
  Optimized build.
  Default target: x86_64-unknown-linux-gnu
  Host CPU: sandybridge

  Registered Targets:
    wasm32 - WebAssembly 32-bit
    wasm64 - WebAssembly 64-bit
    x86    - 32-bit X86: Pentium-Pro and above
    x86-64 - 64-bit X86: EM64T and AMD64
===========================================================================
CRITICAL:root:you can fall back to the older (pre-fastcomp) compiler core, although that is not recommended, see http://kripken.github.io/emscripten-site/docs/building_from_source/LLVM-Backend.html
INFO:root:(Emscripten: Running sanity checks)
CRITICAL:root:Cannot find /tmp/toolchains/emsd/bin/clang++, check the paths in ~/.emscripten

**Comment by Ace17** [comment]
OK forget it, I was using the 'master' emscripten instead of 'incoming'. I'm going to dig further, I'll update this thread with my results later.

**Comment by kripken** [comment]
Should be no need for clang in this path, unless the D frontend needs it somehow.

**Comment by Ace17** [comment]
I finally managed to compile a (limited) D program an run it into the browser!
http://code.alaiwan.org/wp/?p=103

**Comment by Ace17** [comment]
OK it's working now!
Some tiny LDC modifications are still needed, but the intermediate convert-to-C step isn't needed anymore.
The build process for ldc+fastcomp is fully automated in my dscripten repo ( https://github.com/Ace17/dscripten/blob/master/fetch_toolchain ).

(at the moment there's still no support for the D runtime, which means only a subset of the D langage is supported)
